cp src/AutoComplete/AutoComplete.css es/AutoComplete/AutoComplete.css
cp src/Dropdown/Dropdown.css es/Dropdown/Dropdown.css
cp src/Menu/Menu.css es/Menu/Menu.css
cp src/MenuList/MenuList.css es/MenuList/MenuList.css
cp src/MenuItem/MenuItem.css es/MenuItem/MenuItem.css
cp src/SelectField/SelectField.css es/SelectField/SelectField.css
cp src/OptionList/OptionList.css es/OptionList/OptionList.css
cp src/Option/Option.css es/Option/Option.css
cp src/MultiSelectField/MultiSelectField.css es/MultiSelectField/MultiSelectField.css
cp src/Stepper/Stepper.css es/Stepper/Stepper.css
