cp src/AutoComplete/AutoComplete.css lib/AutoComplete/AutoComplete.css
cp src/Dropdown/Dropdown.css lib/Dropdown/Dropdown.css
cp src/Menu/Menu.css lib/Menu/Menu.css
cp src/MenuList/MenuList.css lib/MenuList/MenuList.css
cp src/MenuItem/MenuItem.css lib/MenuItem/MenuItem.css
cp src/SelectField/SelectField.css lib/SelectField/SelectField.css
cp src/OptionList/OptionList.css lib/OptionList/OptionList.css
cp src/Option/Option.css lib/Option/Option.css
cp src/MultiSelectField/MultiSelectField.css lib/MultiSelectField/MultiSelectField.css
cp src/Stepper/Stepper.css lib/Stepper/Stepper.css
