cp src/AutoComplete/AutoComplete.scss lib/AutoComplete/AutoComplete.scss
cp src/Dropdown/Dropdown.scss lib/Dropdown/Dropdown.scss
cp src/Menu/Menu.scss lib/Menu/Menu.scss
cp src/MenuList/MenuList.scss lib/MenuList/MenuList.scss
cp src/MenuItem/MenuItem.scss lib/MenuItem/MenuItem.scss
cp src/SelectField/SelectField.scss lib/SelectField/SelectField.scss
cp src/OptionList/OptionList.scss lib/OptionList/OptionList.scss
cp src/Option/Option.scss lib/Option/Option.scss
cp src/MultiSelectField/MultiSelectField.scss lib/MultiSelectField/MultiSelectField.scss
cp src/Stepper/Stepper.scss lib/Stepper/Stepper.scss
